### ISSUE TITLE
Air Jump Not Working (BUG)

### ISSUE THREAD

**Issue by ZacDoesStuff** [ProjectKorra/AvatarMod#206]
Hello! **My Air jump is not working.** I know how to air jump, and all my friends say that theirs work, but I am not able to. This also means I have a constant "Air Jump" logo on my crosshair. It's really annoying. Does anyone know how to fix this bug? I've tried fixing it in creative and survival, but nothing. Again, I know how to air jump, but it won't let me.

**Comment by FavouriteDragon** [comment]
Mod version? Forge version? Did you rebind your jump key from space?

**Comment by BabenisBest** [comment]
Hi, I'm also having this bug. I'm running the latest version of the mod, 1.5.17, space bar is my jump key, and the Forge version is 1.12.2-14.23.5.2854. Whenever I select the air jump, it shows the symbol under my crosshair but nothing actually happens when I jump. I am playing with a lot of other mods, so please let me know if you want me to list them all

**Comment by BabenisBest** [comment]
> 
> 
> Hi, I'm also having this bug. I'm running the latest version of the mod, 1.5.17, space bar is my jump key, and the Forge version is 1.12.2-14.23.5.2854. Whenever I select the air jump, it shows the symbol under my crosshair but nothing actually happens when I jump. I am playing with a lot of other mods, so please let me know if you want me to list them all

Ah, it seems like having multiple things bound to the space bar is causing the issue. Went through my controls and put everything bound to space besides jump to a different key and the air jump started working just fine.

**Comment by FavouriteDragon** [comment]
This incompatibility error is fixed in 1.6.0.
