### ISSUE TITLE
Cancel Inferno Punch

### ISSUE THREAD

**Issue by AgroFro** [ProjectKorra/AvatarMod#219]
I dont know if there is a way to cancel the inferno punch or not, it would be a convenient feature. If there is no way to cancel, is there a way to downgrade abilities because I'd like to change my final inferno punch ability

**Comment by hdkd4** [comment]
Yes, what you'll want to do, if you already have cheats enabled is type this command into the chat
/avatar xp @p inferno_punch lvl3
This will set the ability to level 3, which you can then enter this command
/avatar ability set @p inferno_punch 100
This will set the ability to fully trained so that you can insert a firebending scroll into the slot you want to upgrade to.

If you don't have cheats enabled, you'll want to press escape, then find the open to LAN button. From there you can activate cheats, which will deactivate once you leave the world. Hope this helps! =D

**Comment by FavouriteDragon** [comment]
Doesn't exist in 1.6.0+. And thanks, hdk!
