### ISSUE TITLE
Server Related Issues...

### ISSUE THREAD

**Issue by R4G1NG-S70RM** [ProjectKorra/AvatarMod#278]
Lately i'm been trying to make a server with the Avatar Mod 2: Out of the Iceberg, but i'm having some problems related to using the bends.
In singleplayer world it works fine, aside being in beta, but when i try playing on the server i can't use any bendings, the game claims that i dont have a bending and that i should use the command /avatar bending add (id), but i tried many times and it dont work, i even tried to use scrolls to unlock the bending abilities, when i right click i'm redirected to the bending hud but i can't unlock the moves using the scrolls.

Sorry for the english mistakes, i hope the devs can solve this quickly, thanks for reading.

**Comment by Dimonchiks488** [comment]
confirm, same problem

**Comment by darthvader45** [comment]
Same problem, running 1.6.2 for 1.12.2.  No idea why. Team Korra, you guys might want to look at this.

**Comment by darthvader45** [comment]
Okay, apparently setting the server/lan world to online mode fixes it.  Try that.

**Comment by usoppsS** [comment]
same i just cant open the menu at all it works perfectly for my friend tho

**Comment by mahtaran** [comment]
This issue is often encountered because of the usage of cracked accounts or servers set to offline-mode, which are not supported, so I'm closing this for now. In case you're not using cracked accounts and/or your server is set to online-mode, please open a new ticket and attach your forge version, mod version, a crash report/log, list of mods, and java version.
